services:
  database:
    image: mysql:8.1.0
    container_name: taskopia-database
    restart: unless-stopped
    networks:
      - taskopia
    ports:
      - 3307:3306
    volumes:
      - ./backend/database/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_ROOT_PASSWORD: password

  backend:
    build: ./backend
    container_name: taskopia-backend
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - taskopia
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    command: mvn spring-boot:run

  backend-tests:
    image: maven:3
    container_name: taskopia-backend-tests
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "mvn test && exit"

  frontend:
    container_name: taskopia-frontend
    build: ./client
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./client/.next:/app/.next
    ports:
      - 3000:3000


networks:
  taskopia:
    name: taskopia
    driver: bridge