CREATE DATABASE IF NOT EXISTS TASKOPIA;

USE TASKOPIA;

CREATE TABLE cards(
    id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
);